"""Derived SQLite concept index (Phase 2).

Provides path resolution, SQLAlchemy Core schema, schema-version handling,
repositories, vault synchronization, lexical search, embeddings, and vector search.
"""

from studium.index.config import (
    DEFAULT_BUSY_TIMEOUT_MS,
    DEFAULT_EMBEDDING_BATCH_SIZE,
    DEFAULT_EMBEDDING_MODEL_ID,
    DEFAULT_RRF_CONSTANT,
    DEFAULT_RRF_WEIGHTS,
    DEFAULT_VECTOR_BACKEND,
    INDEX_SCHEMA_VERSION,
    MAX_MODULE_EMBED_CHARS,
    IndexConfig,
)
from studium.index.embeddings import (
    EmbeddingModelMetadata,
    EmbeddingProcessReport,
    EmbeddingProvider,
    FakeEmbeddingProvider,
    SentenceTransformersEmbeddingProvider,
    SyncAndEmbedReport,
    embed_query,
    enumerate_embedding_work,
    merge_embedding_work,
    pack_vector,
    process_embedding_work,
    sync_and_embed,
    unpack_vector,
)
from studium.index.engine import begin_connection, create_index_engine, read_pragma
from studium.index.errors import (
    ConceptIndexError,
    ConceptNotFoundError,
    IndexIntegrityError,
    IndexNotInitializedError,
    IndexSchemaMismatchError,
)
from studium.index.normalize import normalize_for_lookup, normalize_title
from studium.index.paths import derive_vault_identifier, index_db_path, resolve_application_data_dir
from studium.index.schema_manager import (
    create_engine_for_config,
    ensure_compatible_index,
    get_index_revision,
    increment_index_revision,
    initialize_index,
    read_index_schema_version,
    rebuild_index,
)
from studium.index.search import (
    ConceptSearchFilters,
    ConceptSearchQuery,
    ConceptSearchResult,
    ExactMatchType,
    HybridSearchOptions,
    IdentityResolution,
    LexicalSearchResult,
    ResolutionState,
    SearchStatus,
    resolve_concept_identity,
    search_concepts,
    search_concepts_fts,
    search_concepts_lexical,
    search_modules_fts,
)
from studium.index.sync import (
    EmbeddingWorkRequest,
    SyncCounts,
    SyncReport,
    SyncStatus,
    rebuild_vault_index,
    sync_vault,
)
from studium.index.vector import (
    ModelSpaceFilter,
    NumpyVectorSearchBackend,
    VectorConceptHit,
    VectorModuleHit,
    VectorSearchBackend,
    create_vector_backend,
    search_concept_identity_vectors,
    search_concept_semantic_vectors,
    search_module_semantic_vectors,
)

__all__ = [
    "DEFAULT_BUSY_TIMEOUT_MS",
    "DEFAULT_EMBEDDING_BATCH_SIZE",
    "DEFAULT_EMBEDDING_MODEL_ID",
    "DEFAULT_RRF_CONSTANT",
    "DEFAULT_RRF_WEIGHTS",
    "DEFAULT_VECTOR_BACKEND",
    "INDEX_SCHEMA_VERSION",
    "MAX_MODULE_EMBED_CHARS",
    "ConceptIndexError",
    "ConceptNotFoundError",
    "ConceptSearchFilters",
    "ConceptSearchQuery",
    "ConceptSearchResult",
    "EmbeddingModelMetadata",
    "EmbeddingProcessReport",
    "EmbeddingProvider",
    "EmbeddingWorkRequest",
    "ExactMatchType",
    "FakeEmbeddingProvider",
    "HybridSearchOptions",
    "IdentityResolution",
    "IndexConfig",
    "IndexIntegrityError",
    "IndexNotInitializedError",
    "IndexSchemaMismatchError",
    "LexicalSearchResult",
    "ModelSpaceFilter",
    "NumpyVectorSearchBackend",
    "ResolutionState",
    "SearchStatus",
    "SentenceTransformersEmbeddingProvider",
    "SyncAndEmbedReport",
    "SyncCounts",
    "SyncReport",
    "SyncStatus",
    "VectorConceptHit",
    "VectorModuleHit",
    "VectorSearchBackend",
    "begin_connection",
    "create_engine_for_config",
    "create_index_engine",
    "create_vector_backend",
    "derive_vault_identifier",
    "embed_query",
    "ensure_compatible_index",
    "enumerate_embedding_work",
    "get_index_revision",
    "increment_index_revision",
    "index_db_path",
    "initialize_index",
    "merge_embedding_work",
    "normalize_for_lookup",
    "normalize_title",
    "pack_vector",
    "process_embedding_work",
    "read_index_schema_version",
    "read_pragma",
    "rebuild_index",
    "rebuild_vault_index",
    "resolve_application_data_dir",
    "resolve_concept_identity",
    "search_concept_identity_vectors",
    "search_concept_semantic_vectors",
    "search_concepts",
    "search_concepts_fts",
    "search_concepts_lexical",
    "search_module_semantic_vectors",
    "search_modules_fts",
    "sync_and_embed",
    "sync_vault",
    "unpack_vector",
]
